
        const COLOR_MAP = {
            "000080": { "name": "Tig yn cors", "new_key": "cib_reg_tig_yn_cors", "old_key": "vik_reg_poclintun", "sea": false },
            "0000FF": { "name": "Triker", "new_key": "cib_reg_triker", "old_key": "vik_reg_cissanbyrig", "sea": false },
            "002157": { "name": "Northsae", "new_key": "cib_sea_northsae", "old_key": "nuova regione", "sea": true },
            "003471": { "name": "Muir Sinna", "new_key": "cib_sea_muir_sinna", "old_key": "nuova regione", "sea": true },
            "003663": { "name": "Suthsae", "new_key": "cib_sea_suthsae", "old_key": "nuova regione", "sea": true },
            "004A80": { "name": "Muir Eirenn", "new_key": "cib_sea_muir_eirenn", "old_key": "nuova regione", "sea": true },
            "0054A6": { "name": "Muir Norc", "new_key": "cib_sea_muir_norc", "old_key": "nuova regione", "sea": true },
            "005952": { "name": "Dofere Sund", "new_key": "cib_sea_dofere_sund", "old_key": "nuova regione", "sea": true },
            "005B7F": { "name": "Solentan", "new_key": "cib_sea_solentan", "old_key": "nuova regione", "sea": true },
            "006400": { "name": "Tuaim da Ghualann", "new_key": "cib_reg_tuaim_da_ghualann", "old_key": "vik_reg_tuaim", "sea": false },
            "0072BC": { "name": "Muir Domon", "new_key": "cib_sea_muir_domon", "old_key": "nuova regione", "sea": true },
            "00746B": { "name": "Muir Britton", "new_key": "cib_sea_muir_britton", "old_key": "nuova regione", "sea": true },
            "0076A3": { "name": "Maerse Sae", "new_key": "cib_sea_maerse_sae", "old_key": "nuova regione", "sea": true },
            "008B00": { "name": "Abernanton", "new_key": "cib_reg_abernanton", "old_key": "vik_reg_tor_in_duine", "sea": false },
            "008B45": { "name": "Neen Din", "new_key": "cib_reg_neen_din", "old_key": "vik_reg_northhamtun", "sea": false },
            "008B8B": { "name": "Rath Cruachan", "new_key": "cib_reg_rath_cruachan", "old_key": "nuova regione", "sea": false },
            "009ACD": { "name": "Caisil", "new_key": "cib_reg_caisil", "old_key": "nuova regione", "sea": false },
            "00A99D": { "name": "Sruth Tuaiscert", "new_key": "cib_sea_sruth_tuaiscert", "old_key": "nuova regione", "sea": true },
            "00AEEF": { "name": "Muir Tuaiscert", "new_key": "cib_sea_muir_tuaiscert", "old_key": "nuova regione", "sea": true },
            "00B2EE": { "name": "Caer Penhallgot", "new_key": "cib_reg_caer_penhallgot", "old_key": "vik_reg_totanes", "sea": false },
            "00BFF3": { "name": "Engle Sae", "new_key": "cib_sea_engle_sae", "old_key": "nuova regione", "sea": true },
            "00CD66": { "name": "Dourbruf", "new_key": "cib_reg_dourbruf", "old_key": "vik_reg_rofeceaster", "sea": false },
            "00CED1": { "name": "Dun Loch", "new_key": "cib_reg_dun_loch", "old_key": "vik_reg_inis_faithlenn", "sea": false },
            "00E5EE": { "name": "Ferna", "new_key": "cib_reg_ferna", "old_key": "nuova regione", "sea": false },
            "00EE00": { "name": "Lindon", "new_key": "cib_reg_lindon", "old_key": "vik_reg_lindcylne", "sea": false },
            "00EE76": { "name": "Bodweryn", "new_key": "cib_reg_bodweryn", "old_key": "vik_reg_sancte_ye", "sea": false },
            "00EEEE": { "name": "Tig ar Hul", "new_key": "cib_reg_tig_ar_hul", "old_key": "vik_reg_beoferlic", "sea": false },
            "00FF00": { "name": "Alt Clut", "new_key": "cib_reg_alt_clut", "old_key": "vik_reg_alt_clut", "sea": false },
            "050505": { "name": "Moel Byrn", "new_key": "cib_reg_moel_byrn", "old_key": "vik_reg_wigracestre", "sea": false },
            "080808": { "name": "Dun Cawn", "new_key": "cib_reg_dun_cawn", "old_key": "vik_reg_dugannu", "sea": false },
            "0D004C": { "name": "Muir Deiscert", "new_key": "cib_sea_muir_deiscert", "old_key": "nuova regione", "sea": true },
            "104E8B": { "name": "Lochduin", "new_key": "cib_reg_lochduin", "old_key": "vik_reg_airchardan", "sea": false },
            "121212": { "name": "Corda", "new_key": "cib_reg_corda", "old_key": "cib_reg_corda", "sea": false },
            "1ABBB4": { "name": "Linne Forthin", "new_key": "cib_sea_linne_forthin", "old_key": "nuova regione", "sea": true },
            "1B1464": { "name": "Engle Sund", "new_key": "cib_sea_engle_sund", "old_key": "nuova regione", "sea": true },
            "1F1F1F": { "name": "Tuam Greine", "new_key": "cib_reg_tuam_greine", "old_key": "nuova regione", "sea": false },
            "242424": { "name": "Sefeldion", "new_key": "cib_reg_sefeldion", "old_key": "vik_reg_dor", "sea": false },
            "262626": { "name": "Rǵos Dun", "new_key": "cib_reg_rgos_dun", "old_key": "vik_reg_basengas", "sea": false },
            "27408B": { "name": "Achadh Bo", "new_key": "cib_reg_achadh_bo", "old_key": "nuova regione", "sea": false },
            "2E3192": { "name": "Linne Moreb", "new_key": "cib_sea_linne_moreb", "old_key": "nuova regione", "sea": true },
            "2E8B57": { "name": "Londonjon", "new_key": "cib_reg_londonjon", "old_key": "vik_reg_lunden", "sea": false },
            "303030": { "name": "Striveling", "new_key": "cib_reg_striveling", "old_key": "vik_reg_sreth_belin", "sea": false },
            "333333": { "name": "Caerbron", "new_key": "cib_reg_caerbron", "old_key": "vik_reg_ros_cuissine", "sea": false },
            "3CB371": { "name": "Axanbryc", "new_key": "cib_reg_axanbryc", "old_key": "vik_reg_axanbrycg", "sea": false },
            "3D3D3D": { "name": "Pefenesea", "new_key": "cib_reg_pefenesea", "old_key": "nuova regione", "sea": false },
            "40E0D0": { "name": "Cluain Mor", "new_key": "cib_reg_cluain_mor", "old_key": "nuova regione", "sea": false },
            "4169E1": { "name": "Burg lgas", "new_key": "cib_reg_burg_lgas", "old_key": "vik_reg_cirenceaster", "sea": false },
            "424242": { "name": "Rerigon", "new_key": "cib_reg_rerigon", "old_key": "vik_reg_brechin", "sea": false },
            "436EEE": { "name": "Dun Sebuirgi", "new_key": "cib_reg_dun_sebuirgi", "old_key": "nuova regione", "sea": false },
            "448CCB": { "name": "Seaxe Sae", "new_key": "cib_sea_seaxe_sae", "old_key": "nuova regione", "sea": true },
            "458B00": { "name": "Sligeach", "new_key": "cib_reg_sligeach", "old_key": "vik_reg_cnodba", "sea": false },
            "48D1CC": { "name": "Eburākon", "new_key": "cib_reg_eburakon", "old_key": "vik_reg_eoferwic", "sea": false },
            "4D4D4D": { "name": "Loch in aice bá", "new_key": "cib_reg_loch_in_aice_ba", "old_key": "vik_reg_haestingas", "sea": false },
            "4EEE94": { "name": "Caer Myrddin", "new_key": "cib_reg_caer_myrddin", "old_key": "vik_reg_cair_mirddin", "sea": false },
            "4F94CD": { "name": "Ffyn y Nant", "new_key": "cib_reg_ffyn_y_nant", "old_key": "vik_reg_wyrcesuuyrthe", "sea": false },
            "53868B": { "name": "Cathair Domnaill", "new_key": "cib_reg_cathair_domnaill", "old_key": "nuova regione", "sea": false },
            "54FF9F": { "name": "Portus Itius", "new_key": "cib_reg_portus_itius", "old_key": "cib_reg_portus_itius", "sea": false },
            "575757": { "name": "Caer Taff", "new_key": "cib_reg_caer_taff", "old_key": "vik_reg_dinas_powis", "sea": false },
            "595959": { "name": "Inis Sibhtonn", "new_key": "cib_reg_inis_sibhtonn", "old_key": "vik_reg_hlymrekr", "sea": false },
            "5A50BE": { "name": "Loch Eochaid", "new_key": "cib_sea_loch_eochaid", "old_key": "nuova regione", "sea": true },
            "5B4DC2": { "name": "Lake", "new_key": "cib_sea_lake", "old_key": "nuova regione", "sea": true },
            "5C5C5C": { "name": "Cair Tamas", "new_key": "cib_reg_cair_tamas", "old_key": "vik_reg_tamworthige", "sea": false },
            "5CACEE": { "name": "Ratumacos", "new_key": "cib_reg_ratumacos", "old_key": "cib_reg_ratumacos", "sea": false },
            "5E5E5E": { "name": "Brannodunion", "new_key": "cib_reg_brannodunion", "old_key": "vik_reg_aelmham", "sea": false },
            "5F9EA0": { "name": "Gleann Da Loch", "new_key": "cib_reg_gleann_da_loch", "old_key": "nuova regione", "sea": false },
            "636363": { "name": "Cluain", "new_key": "cib_reg_cluain", "old_key": "nuova regione", "sea": false },
            "6495ED": { "name": "Verlamion", "new_key": "cib_reg_verlamion", "old_key": "vik_reg_sancte_albanes", "sea": false },
            "668B8B": { "name": "Cluain Iraird", "new_key": "cib_reg_cluain_iraird", "old_key": "nuova regione", "sea": false },
            "66CDAA": { "name": "Venta", "new_key": "cib_reg_venta", "old_key": "vik_reg_wintanceaster", "sea": false },
            "6852CD": { "name": "Mare Incognita", "new_key": "cib_sea_mare_incognita", "old_key": "nuova regione", "sea": true },
            "6959CD": { "name": "Lis Mor", "new_key": "cib_reg_lis_mor", "old_key": "nuova regione", "sea": false },
            "696969": { "name": "Cluain Mac Nois", "new_key": "cib_reg_cluain_mac_nois", "old_key": "nuova regione", "sea": false },
            "696B69": { "name": "Læwe", "new_key": "cib_reg_læwe", "old_key": "vik_reg_laewe", "sea": false },
            "698B22": { "name": "Tre ar Sturr", "new_key": "cib_reg_tre_ar_sturr", "old_key": "vik_reg_sancte_eadmundes", "sea": false },
            "698B69": { "name": "Imblech Ibair", "new_key": "cib_reg_imblech_ibair", "old_key": "nuova regione", "sea": false },
            "707070": { "name": "Durou̯ernon", "new_key": "cib_reg_durouernon", "old_key": "vik_reg_cantwaraburg", "sea": false },
            "76EEC6": { "name": "Dwfr ker", "new_key": "cib_reg_dwfr_ker", "old_key": "vik_reg_dofere", "sea": false },
            "787878": { "name": "Bun Ilidh", "new_key": "cib_reg_bun_ilidh", "old_key": "vik_reg_torfness", "sea": false },
            "7A67EE": { "name": "Dun Tagel", "new_key": "cib_reg_dun_tagel", "old_key": "vik_reg_tintagol", "sea": false },
            "7A8B8B": { "name": "Dun Ailinne", "new_key": "cib_reg_dun_ailinne", "old_key": "vik_reg_nas", "sea": false },
            "7AC5CD": { "name": "Pont war Weolud", "new_key": "cib_reg_pont_war_weolud", "old_key": "vik_reg_steanford", "sea": false },
            "7B68EE": { "name": "Lētocaiton", "new_key": "cib_reg_letocaiton", "old_key": "vik_reg_licetfelda", "sea": false },
            "7CFC00": { "name": "Cilurnum", "new_key": "cib_reg_cilurnum", "old_key": "vik_reg_heslerton", "sea": false },
            "7D7D7D": { "name": "Druim Collachair", "new_key": "cib_reg_druim_collachair", "old_key": "nuova regione", "sea": false },
            "813626": { "name": "Caer Eidyn", "new_key": "cib_reg_caer_eidyn", "old_key": "vik_reg_eidenburg", "sea": false },
            "82616E": { "name": "Dunmore ring", "new_key": "cib_reg_dunmore_ring", "old_key": "vik_reg_hereford", "sea": false },
            "826EFA": { "name": "Cilta", "new_key": "cib_reg_cilta", "old_key": "vik_reg_gleawceaster", "sea": false },
            "828282": { "name": "Lle ffynnon", "new_key": "cib_reg_lle_ffynnon", "old_key": "vik_reg_herutford", "sea": false },
            "836FFF": { "name": "Bibrax", "new_key": "cib_reg_bibrax", "old_key": "cib_reg_bibrax", "sea": false },
            "838B83": { "name": "Ardach", "new_key": "cib_reg_ardach", "old_key": "nuova regione", "sea": false },
            "878787": { "name": "Caere Badon", "new_key": "cib_reg_caere_badon", "old_key": "vik_reg_bathanceaster", "sea": false },
            "88CEFF": { "name": "Tre uwch Baddow", "new_key": "cib_reg_tre_uwch_baddow", "old_key": "vik_reg_celmeresfort", "sea": false },
            "8968CD": { "name": "Dun Na Ngall", "new_key": "cib_reg_dun_na_ngall", "old_key": "nuova regione", "sea": false },
            "8A8A8A": { "name": "Dun Prys", "new_key": "cib_reg_dun_prys", "old_key": "vik_reg_din_prys", "sea": false },
            "8B0000": { "name": "Loch Gabhair", "new_key": "cib_reg_loch_gabhair", "old_key": "nuova regione", "sea": false },
            "8B008B": { "name": "Dun Dwfr", "new_key": "cib_reg_dun_dwfr", "old_key": "vik_reg_doreceaster", "sea": false },
            "8B1A1A": { "name": "Llwyn y Brain", "new_key": "cib_reg_llwyn_y_brain", "old_key": "vik_reg_lann_idloes", "sea": false },
            "8B2500": { "name": "Din Usa", "new_key": "cib_reg_din_usa", "old_key": "vik_reg_theodford", "sea": false },
            "8B3A62": { "name": "Dun Menez", "new_key": "cib_reg_dun_menez", "old_key": "vik_reg_sceaftesburg", "sea": false },
            "8B4726": { "name": "Dun Droma", "new_key": "cib_reg_dun_droma", "old_key": "vik_reg_dun_patraic", "sea": false },
            "8B475D": { "name": "Samarobriva", "new_key": "cib_reg_samarobriva", "old_key": "cib_reg_samarobriva", "sea": false },
            "8B668B": { "name": "Bodun", "new_key": "cib_reg_bodun", "old_key": "vik_reg_exanceaster", "sea": false },
            "8B6914": { "name": "Din Lligwy", "new_key": "cib_reg_din_lligwy", "old_key": "vik_reg_aberffro", "sea": false },
            "8B6969": { "name": "Cuan Modha", "new_key": "cib_reg_cuan_modha", "old_key": "vik_reg_ros", "sea": false },
            "8B7500": { "name": "Dùn Bheccáin", "new_key": "cib_reg_dun_bheccain", "old_key": "vik_reg_dun_beccan", "sea": false },
            "8B7B8B": { "name": "Dun Kerc'h", "new_key": "cib_reg_dun_kerch", "old_key": "vik_reg_werham", "sea": false },
            "8B7D6B": { "name": "Lann Cors", "new_key": "cib_reg_lann_cors", "old_key": "nuova regione", "sea": false },
            "8B8378": { "name": "Tulach", "new_key": "cib_reg_tulach", "old_key": "vik_reg_dun_cailden", "sea": false },
            "8B8682": { "name": "Isurium", "new_key": "cib_reg_isurium", "old_key": "vik_reg_lude", "sea": false },
            "8B8878": { "name": "Caersws", "new_key": "cib_reg_caersws", "old_key": "vik_reg_mathrafal", "sea": false },
            "8B8970": { "name": "Oban", "new_key": "cib_reg_oban", "old_key": "vik_reg_dun_ollaig", "sea": false },
            "8B8B00": { "name": "Mynyw", "new_key": "cib_reg_mynyw", "old_key": "vik_reg_menevia", "sea": false },
            "8EE5EE": { "name": "Touesis", "new_key": "cib_reg_touesis", "old_key": "vik_reg_dear", "sea": false },
            "8F8F8F": { "name": "Coinnire", "new_key": "cib_reg_coinnire", "old_key": "nuova regione", "sea": false },
            "8FBC8F": { "name": "Camulodunon", "new_key": "cib_reg_camulodunon", "old_key": "vik_reg_colneceaster", "sea": false },
            "912CEE": { "name": "Durocobrivis", "new_key": "cib_reg_durocobrivis", "old_key": "vik_reg_buccingahamm", "sea": false },
            "919191": { "name": "Corcach", "new_key": "cib_reg_corcach", "old_key": "nuova regione", "sea": false },
            "9370DB": { "name": "Ard Sratha", "new_key": "cib_reg_ard_sratha", "old_key": "nuova regione", "sea": false },
            "969696": { "name": "Aporcrosan", "new_key": "cib_reg_aporcrosan", "old_key": "vik_reg_aporcrosan", "sea": false },
            "9A32CD": { "name": "Drom an Iarainn", "new_key": "cib_reg_drom_an_iarainn", "old_key": "vik_reg_cell_cainning", "sea": false },
            "9AC0CD": { "name": "Rauatonion", "new_key": "cib_reg_rauatonion", "old_key": "vik_reg_dun_aberte", "sea": false },
            "9AFF9A": { "name": "Coed agos traeth", "new_key": "cib_reg_coed_agos_traeth", "old_key": "vik_reg_rendlesham", "sea": false },
            "9B30FF": { "name": "Cuala", "new_key": "cib_reg_cuala", "old_key": "vik_reg_seolesigge", "sea": false },
            "9C9C9C": { "name": "Tre'r Cewri", "new_key": "cib_reg_trer_cewri", "old_key": "vik_reg_cair_segeint", "sea": false },
            "9DB6CD": { "name": "Y Gaer Fawr", "new_key": "cib_reg_y_gaer_fawr", "old_key": "vik_reg_dinefwr", "sea": false },
            "A020F0": { "name": "Sceap Dun", "new_key": "cib_reg_sceap_dun", "old_key": "vik_reg_tureceseig", "sea": false },
            "A0522D": { "name": "Hamdon", "new_key": "cib_reg_hamdon", "old_key": "vik_reg_scireburnan", "sea": false },
            "A2CD5A": { "name": "Grianan Aileach", "new_key": "cib_reg_grianan_aileach", "old_key": "nuova regione", "sea": false },
            "A3A3A3": { "name": "Aberness", "new_key": "cib_reg_aberness", "old_key": "vik_reg_inber_nise", "sea": false },
            "A6A6A6": { "name": "Cell Alaid", "new_key": "cib_reg_cell_alaid", "old_key": "nuova regione", "sea": false },
            "ADADAD": { "name": "Luguwalion", "new_key": "cib_reg_luguwalion", "old_key": "vik_reg_carleol", "sea": false },
            "AFEEEE": { "name": "Loch Raich", "new_key": "cib_reg_loch_raich", "old_key": "nuova regione", "sea": false },
            "B03060": { "name": "Rhwospen", "new_key": "cib_reg_rhwospen", "old_key": "vik_reg_hwitan_aerne", "sea": false },
            "B0B0B0": { "name": "Ratae", "new_key": "cib_reg_ratae", "old_key": "vik_reg_ligeraceaster", "sea": false },
            "B0D8E6": { "name": "Bratus", "new_key": "cib_reg_bratus", "old_key": "cib_reg_bratus", "sea": false },
            "B0E0E6": { "name": "Men Aber", "new_key": "cib_reg_men_aber", "old_key": "vik_reg_dun_foither", "sea": false },
            "B0E2FF": { "name": "Cell Maic Aeda", "new_key": "cib_reg_cell_maic_aeda", "old_key": "nuova regione", "sea": false },
            "B22222": { "name": "Cathair Commain", "new_key": "cib_reg_cathair_commain", "old_key": "nuova regione", "sea": false },
            "B23AEE": { "name": "Derdriun", "new_key": "cib_reg_derdriun", "old_key": "vik_reg_dun_nechtain", "sea": false },
            "B3EE3A": { "name": "Dun Firth", "new_key": "cib_reg_dun_firth", "old_key": "vik_reg_guldeford", "sea": false },
            "B4CDCD": { "name": "Gortomagos", "new_key": "cib_reg_gortomagos", "old_key": "vik_reg_sconnin", "sea": false },
            "B4EEB4": { "name": "Ard Mor", "new_key": "cib_reg_ard_mor", "old_key": "nuova regione", "sea": false },
            "B5B5B5": { "name": "Gurnbrough", "new_key": "cib_reg_gurnbrough", "old_key": "vik_reg_blascona", "sea": false },
            "B8B8B8": { "name": "Aber Don", "new_key": "cib_reg_aber_don", "old_key": "vik_reg_abberdeon", "sea": false },
            "B9D3EE": { "name": "Tre Weir", "new_key": "cib_reg_tre_weir", "old_key": "vik_reg_waerincwicum", "sea": false },
            "BA55D3": { "name": "Tig ar y Aber", "new_key": "cib_reg_tig_ar_y_aber", "old_key": "vik_reg_flichesburg", "sea": false },
            "BBFFFF": { "name": "Emain Macha", "new_key": "cib_reg_emain_macha", "old_key": "vik_reg_ard_macha", "sea": false },
            "BC8F8F": { "name": "Alauna", "new_key": "cib_reg_alauna", "old_key": "cib_reg_alauna", "sea": false },
            "BCD2EE": { "name": "Elge", "new_key": "cib_reg_elge", "old_key": "vik_reg_elig", "sea": false },
            "BCEE68": { "name": "Cwm Bran", "new_key": "cib_reg_cwm_bran", "old_key": "vik_reg_lann_afan", "sea": false },
            "BF3EFF": { "name": "Dina Briwa", "new_key": "cib_reg_dina_briwa", "old_key": "vik_reg_grantabrycg", "sea": false },
            "C0FF3E": { "name": "Carmore", "new_key": "cib_reg_carmore", "old_key": "vik_reg_aebburcurnig", "sea": false },
            "C70738": { "name": "Terra Incognita", "new_key": "cib_reg_terra_incognita", "old_key": "nuova regione", "sea": false },
            "C71585": { "name": "Nedd", "new_key": "cib_reg_nedd", "old_key": "vik_reg_nedd", "sea": false },
            "C7C7C7": { "name": "Dun Co Abon Granta", "new_key": "cib_reg_dun_co_abon_granta", "old_key": "vik_reg_aethelingaeg", "sea": false },
            "CAE1FF": { "name": "Mwd Din", "new_key": "cib_reg_mwd_din", "old_key": "vik_reg_drayton", "sea": false },
            "CAFF70": { "name": "Veisafjordr", "new_key": "cib_reg_veisafjordr", "old_key": "nuova regione", "sea": false },
            "CCCCCC": { "name": "Wextsetla", "new_key": "cib_reg_wextsetla", "old_key": "vik_reg_wiht", "sea": false },
            "CD0000": { "name": "Mamnos", "new_key": "cib_reg_mamnos", "old_key": "vik_reg_mameceaster", "sea": false },
            "CD1076": { "name": "Dun Ad", "new_key": "cib_reg_dun_ad", "old_key": "vik_reg_dun_att", "sea": false },
            "CD2990": { "name": "Vedrafjordr", "new_key": "cib_reg_vedrafjordr", "old_key": "nuova regione", "sea": false },
            "CD3278": { "name": "Mowdacch", "new_key": "cib_reg_mowdacch", "old_key": "vik_reg_middeherst", "sea": false },
            "CD3333": { "name": "Lann Ildut", "new_key": "cib_reg_lann_ildut", "old_key": "nuova regione", "sea": false },
            "CD3700": { "name": "Dun Tamor", "new_key": "cib_reg_dun_tamor", "old_key": "vik_reg_liwtune", "sea": false },
            "CD5A96": { "name": "Ard Fert", "new_key": "cib_reg_ard_fert", "old_key": "nuova regione", "sea": false },
            "CD5B45": { "name": "Caer Venta", "new_key": "cib_reg_caer_venta", "old_key": "vik_reg_cair_gwent", "sea": false },
            "CD69C9": { "name": "Noviomagos", "new_key": "cib_reg_noviomagos", "old_key": "cib_reg_noviomagos", "sea": false },
            "CD7054": { "name": "Droche-brig", "new_key": "cib_reg_drochebrig", "old_key": "vik_reg_rocheberie", "sea": false },
            "CD8500": { "name": "Tanet", "new_key": "cib_reg_tanet", "old_key": "vik_reg_tanet", "sea": false },
            "CD9B9B": { "name": "Noviodunum", "new_key": "cib_reg_noviodunum", "old_key": "cib_reg_noviodunum", "sea": false },
            "CDAF95": { "name": "Broc'h lec'h", "new_key": "cib_reg_broch_lech", "old_key": "vik_reg_wiltun", "sea": false },
            "CDB38B": { "name": "Drochaidh", "new_key": "cib_reg_drochaidh", "old_key": "vik_reg_dun_domnaill", "sea": false },
            "CDBA96": { "name": "Clocher", "new_key": "cib_reg_clocher", "old_key": "nuova regione", "sea": false },
            "CDBE70": { "name": "Karn Briga", "new_key": "cib_reg_karn_briga", "old_key": "vik_reg_bodmine", "sea": false },
            "CDC1C5": { "name": "Droim Menaich", "new_key": "cib_reg_droim_menaich", "old_key": "vik_reg_na_seciri", "sea": false },
            "CDC5BF": { "name": "Caer Ogyrfan", "new_key": "cib_reg_caer_ogyrfan", "old_key": "vik_reg_oswaldestroe", "sea": false },
            "CDCDB4": { "name": "Caer Wear", "new_key": "cib_reg_caer_wear", "old_key": "vik_reg_gyruum", "sea": false },
            "CFCFCF": { "name": "Dun Nan Gall", "new_key": "cib_reg_dun_nan_gall", "old_key": "vik_reg_ioua", "sea": false },
            "D1D1D1": { "name": "Saigher", "new_key": "cib_reg_saigher", "old_key": "nuova regione", "sea": false },
            "D1EEEE": { "name": "Gipesbae", "new_key": "cib_reg_gipesbae", "old_key": "vik_reg_gipeswic", "sea": false },
            "D2B48C": { "name": "Din Bar", "new_key": "cib_reg_din_bar", "old_key": "vik_reg_dynbaer", "sea": false },
            "D4D4D4": { "name": "Ebudes", "new_key": "cib_reg_ebudes", "old_key": "vik_reg_stornochway", "sea": false },
            "D6D6D6": { "name": "Ceathair Maol", "new_key": "cib_reg_ceathair_maol", "old_key": "vik_reg_balla", "sea": false },
            "D9D9D9": { "name": "Druim Da Ethiar", "new_key": "cib_reg_druim_da_ethiar", "old_key": "nuova regione", "sea": false },
            "DA70D6": { "name": "Latharna", "new_key": "cib_reg_latharna", "old_key": "nuova regione", "sea": false },
            "DAA520": { "name": "Rudglann", "new_key": "cib_reg_rudglann", "old_key": "nuova regione", "sea": false },
            "DB7093": { "name": "Cell Mor", "new_key": "cib_reg_cell_mor", "old_key": "nuova regione", "sea": false },
            "DDA0DD": { "name": "Lātēnses", "new_key": "cib_reg_latenses", "old_key": "vik_reg_loidis", "sea": false },
            "DEB887": { "name": "Ros Mhaircnidh", "new_key": "cib_reg_ros_mhaircnidh", "old_key": "vik_reg_ros_maircind", "sea": false },
            "E0669B": { "name": "Bodfford", "new_key": "cib_reg_bodfford", "old_key": "vik_reg_cridiatune", "sea": false },
            "E0EEE0": { "name": "Dunholm", "new_key": "cib_reg_dunholm", "old_key": "nuova regione", "sea": false },
            "E0EEEE": { "name": "Dinas Maelor", "new_key": "cib_reg_dinas_maelor", "old_key": "vik_reg_lann_padarn", "sea": false },
            "E0FFFF": { "name": "Cairlinn", "new_key": "cib_reg_cairlinn", "old_key": "nuova regione", "sea": false },
            "E3E3E3": { "name": "Dun Moricambe", "new_key": "cib_reg_dun_moricambe", "old_key": "vik_reg_lonceaster", "sea": false },
            "E664B9": { "name": "Aberteifi", "new_key": "cib_reg_aberteifi", "old_key": "vik_reg_aberteifi", "sea": false },
            "E68AE6": { "name": "Eblana", "new_key": "cib_reg_eblana", "old_key": "vik_reg_dyflin", "sea": false },
            "EE3A8C": { "name": "Rath Luraig", "new_key": "cib_reg_rath_luraig", "old_key": "nuova regione", "sea": false },
            "EE3B3B": { "name": "Caracotinum", "new_key": "cib_reg_caracotinum", "old_key": "cib_reg_caracotinum", "sea": false },
            "EE5C42": { "name": "Hæferfordd", "new_key": "cib_reg_hæferfordd", "old_key": "vik_reg_haverfordia", "sea": false },
            "EE64AD": { "name": "Dún na Ramhainn Aon", "new_key": "cib_reg_dun_na_ramhainn_aon", "old_key": "vik_reg_porteceaster", "sea": false },
            "EE7621": { "name": "Caer Caradog", "new_key": "cib_reg_caer_caradog", "old_key": "vik_reg_brug", "sea": false },
            "EE7942": { "name": "Ráth an Draoí", "new_key": "cib_reg_rath_an_draoi", "old_key": "vik_reg_cluain_eoais", "sea": false },
            "EE799F": { "name": "Colen Bryn", "new_key": "cib_reg_colen_bryn", "old_key": "vik_reg_inis_patraic", "sea": false },
            "EE9A49": { "name": "Inbhir Theòrsa", "new_key": "cib_reg_inbhir_theorsa", "old_key": "vik_reg_thursa", "sea": false },
            "EEA964": { "name": "Dūno uper Abona", "new_key": "cib_reg_duno_uper_abona", "old_key": "vik_reg_cippanhamm", "sea": false },
            "EEAD0E": { "name": "Càrn Smeart", "new_key": "cib_reg_carn_smeart", "old_key": "vik_reg_latharn", "sea": false },
            "EEB422": { "name": "Cathures", "new_key": "cib_reg_cathures", "old_key": "vik_reg_guvan", "sea": false },
            "EEC900": { "name": "Linns", "new_key": "cib_reg_linns", "old_key": "nuova regione", "sea": false },
            "EECFA1": { "name": "Tas Din", "new_key": "cib_reg_tas_din", "old_key": "vik_reg_northwic", "sea": false },
            "EED2EE": { "name": "Tig Guocobauc", "new_key": "cib_reg_tig_guocobauc", "old_key": "vik_reg_snotingaham", "sea": false },
            "EED5B7": { "name": "Dervention", "new_key": "cib_reg_dervention", "old_key": "vik_reg_deoraby", "sea": false },
            "EED5D2": { "name": "Nemetocenna", "new_key": "cib_reg_nemetocenna", "old_key": "cib_reg_nemetocenna", "sea": false },
            "EEDD82": { "name": "Dun Knaus-borg", "new_key": "cib_reg_dun_knausborg", "old_key": "vik_reg_cell_daltain", "sea": false },
            "EEDFCC": { "name": "An Tinbhear Mor", "new_key": "cib_reg_an_tinbhear_mor", "old_key": "nuova regione", "sea": false },
            "EEE0E5": { "name": "Din Gefron", "new_key": "cib_reg_din_gefron", "old_key": "vik_reg_bebbanburg", "sea": false },
            "EEE5DE": { "name": "Inhrypum", "new_key": "cib_reg_inhrypum", "old_key": "vik_reg_hripum", "sea": false },
            "F08080": { "name": "Skipton", "new_key": "cib_reg_skipton", "old_key": "vik_reg_alclyt", "sea": false },
            "F0E68C": { "name": "Durtun", "new_key": "cib_reg_durtun", "old_key": "vik_reg_ethandun", "sea": false },
            "F4F4F4": { "name": "Din pelydr", "new_key": "cib_reg_din_pelydr", "old_key": "vik_reg_coldingaham", "sea": false },
            "F5DEB3": { "name": "Ictinovium", "new_key": "cib_reg_ictinovium", "old_key": "vik_reg_suthhamtun", "sea": false },
            "F5F5DC": { "name": "Caleto Dubro", "new_key": "cib_reg_caleto_dubro", "old_key": "vik_reg_dun_duirn", "sea": false },
            "F5F5F5": { "name": "Crociatonum", "new_key": "cib_reg_crociatonum", "old_key": "cib_reg_crociatonum", "sea": false },
            "F8F8FF": { "name": "Dun Alt", "new_key": "cib_reg_dun_alt", "old_key": "vik_reg_casteltoun", "sea": false },
            "FA8072": { "name": "Brocolition", "new_key": "cib_reg_brocolition", "old_key": "vik_reg_hagustaldes", "sea": false },
            "FAF0E6": { "name": "Eil Dun", "new_key": "cib_reg_eil_dun", "old_key": "vik_reg_mailros", "sea": false },
            "FAFAFA": { "name": "An Toot", "new_key": "cib_reg_an_toot", "old_key": "vik_reg_bedanford", "sea": false },
            "FF0000": { "name": "Cair Daun", "new_key": "cib_reg_cair_daun", "old_key": "vik_reg_doneceaster", "sea": false },
            "FF1493": { "name": "Allt Dun", "new_key": "cib_reg_allt_dun", "old_key": "vik_reg_dacor", "sea": false },
            "FF3030": { "name": "Uriconion", "new_key": "cib_reg_uriconion", "old_key": "vik_reg_scrobbesburg", "sea": false },
            "FF3E96": { "name": "Lemanae", "new_key": "cib_reg_lemanae", "old_key": "vik_reg_stutfall", "sea": false },
            "FF4040": { "name": "Cataractonion", "new_key": "cib_reg_cataractonion", "old_key": "vik_reg_cetretha", "sea": false },
            "FF4500": { "name": "Bealach Dair", "new_key": "cib_reg_bealach_dair", "old_key": "vik_reg_rinnin", "sea": false },
            "FF5CCB": { "name": "Moige Bile", "new_key": "cib_reg_moige_bile", "old_key": "nuova regione", "sea": false },
            "FF6347": { "name": "Dùn Mhùlan", "new_key": "cib_reg_dun_mhulan", "old_key": "vik_reg_bornais", "sea": false },
            "FF7256": { "name": "Cors Crin", "new_key": "cib_reg_cors_crin", "old_key": "vik_reg_wigingamere", "sea": false },
            "FF7F00": { "name": "Wogoced", "new_key": "cib_reg_wogoced", "old_key": "vik_reg_waecet", "sea": false },
            "FF8C00": { "name": "Teamhair", "new_key": "cib_reg_teamhair", "old_key": "vik_reg_cenannas", "sea": false },
            "FFC11B": { "name": "Inis Cathaigh", "new_key": "cib_reg_inis_cathaigh", "old_key": "nuova regione", "sea": false },
            "FFD39B": { "name": "Ivernia", "new_key": "cib_reg_ivernia", "old_key": "vik_reg_ros_ailithir", "sea": false },
            "FFDEAD": { "name": "Fofaras", "new_key": "cib_reg_fofaras", "old_key": "vik_reg_forais", "sea": false },
            "FFE4B5": { "name": "Gunia", "new_key": "cib_reg_gunia", "old_key": "vik_reg_ceaster", "sea": false },
            "FFE7BA": { "name": "Mai Dun", "new_key": "cib_reg_mai_dun", "old_key": "vik_reg_brideport", "sea": false },
            "FFEBCD": { "name": "Caer Cunobelinos", "new_key": "cib_reg_caer_cunobelinos", "old_key": "vik_reg_oxnaforda", "sea": false },
            "FFEC8B": { "name": "Lann Dewi", "new_key": "cib_reg_lann_dewi", "old_key": "nuova regione", "sea": false },
            "FFEFD5": { "name": "Lifer Pol", "new_key": "cib_reg_lifer_pol", "old_key": "vik_reg_otergimele", "sea": false },
            "FFF8DC": { "name": "Keer-ford", "new_key": "cib_reg_keerford", "old_key": "vik_reg_cherchebi", "sea": false },
            "FFFACD": { "name": "Dun De", "new_key": "cib_reg_dun_de", "old_key": "vik_reg_dun_eachainn", "sea": false }
        };
